export const defaultValues = {
        title: '',
        color: '',
        descriptionUa: '',
        descriptionEn: '',
        tagsUa1: '',
        tagsUa2: '',
        tagsUa3: '',
        tagsUa4: '',
        tagsEn1: '',
        tagsEn2: '',
        tagsEn3: '',
        tagsEn4: '',
        courseDescriptionUa1: '',
        courseDescriptionEn1: '',
        startDateUa: '',
        startDateEn: '',
        courseDurationUa: '',
        courseDurationEn: '',
        priceUa: '',
        priceEn: '',
        fullpriceUa: '',
        fullpriceEn: '',
        numberOfPlacesUa: '',
        numberOfPlacesEn: '',
        themeTitleUa: '',
        themeTitleEn: '',
        themesUa1: '',themesUa2: '',themesUa3: '',themesUa4: '', themesUa5: '', themesUa6: '', themesUa7: '',themesUa8: '',themesUa9: '',
        themesUa10: '',themesUa11: '',themesUa12: '',themesUa13: '',themesUa14: '', themesUa15: '',themesUa16: '',themesUa17: '',themesUa18: '',
        themesEn1: '',themesEn2: '',themesEn3: '',themesEn4: '', themesEn5: '', themesEn6: '', themesEn7: '',themesEn8: '',themesEn9: '',
        themesEn10: '',themesEn11: '',themesEn12: '',themesEn13: '',themesEn14: '', themesEn15: '',themesEn16: '',themesEn17: '',themesEn18: '',
        faqUa1: '',
        faqEn1: '',
        faqUa2: '',
        faqEn2: '',
        faqUa3: '',
        faqEn3: '',
        faqUa4: '',
        faqEn4: '',
        faqUa5: '',
        faqEn5: '',
        answerUa1: '',
        answerUa2: '',
        answerUa3: '',
        answerUa4: '',
        answerUa5: '',
        answerEn1: '',
        answerEn2: '',
        answerEn3: '',
        answerEn4: '',
        answerEn5: '',
        teacherId: { value: '', label: ''}
}