import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
import './globals.css'

const fixelDisplay = localFont({
  src: [
    {
      path: '../../public/fonts/FixelDisplay-ExtraLight.woff2',
      weight: '100',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-Light.woff2',
      weight: '200',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-Thin.woff2',
      weight: '300',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-Regular.woff2',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-Medium.woff2',
      weight: '500',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-SemiBold.woff2',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../../public/fonts/FixelDisplay-Bold.woff2',
      weight: '800',
      style: 'normal'
    }
  ]
})

export const metadata: Metadata = {
  title: 'MindLab',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/favicon.png',
      href: '/favicon.png'
    }
  }
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="uk" className={fixelDisplay.className}>
      <body>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
